# Generated by Django 4.1.5 on 2023-02-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_rename_is_personal_user_is_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
